name: Setup Java, GraalVM and Gradle
description: Shared setup for Java, GraalVM and Gradle
inputs:
  java-version:
    description: Java version to setup
    required: true
  enable-graalvm:
    description: Whether to setup GraalVM
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup Java ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}

    - name: Setup GraalVM ${{ inputs.java-version }}
      if: ${{ inputs.enable-graalvm == 'true' }}
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'graalvm-community'
        github-token: ${{ env.GITHUB_TOKEN }}
        native-image-job-reports: 'true'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4