name: "Test"

on:
  push:
    branches:
      - '**'
jobs:
  test:
    name: Test Updated Modules
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup Java and Gradle
        uses: ./.github/actions/setup-java-gradle
        with:
          java-version: '23'
          enable-graalvm: 'false'

      - name: Build with Gradle
        run: ./gradlew check